---
version: '3.5'
services:
  # @see https://hub.docker.com/_/mysql/
  db:
    image: mysql:5.7.22
    volumes:
      - db:/var/lib/mysql
      - ./config/mysql:/etc/mysql/conf.d:ro
    ports:
      - $DOCKER_HOST_DB_PORT:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1

  # @see https://hub.docker.com/r/whilp/ssh-agent/
  ssh:
    image: whilp/ssh-agent
    volumes:
      - ssh:/ssh

  mail:
    build: .
    command: mailcatcher -f --ip=0.0.0.0
    ports:
      - 1025
      - $DOCKER_HOST_MAIL_CATCHER_HTTP_PORT:1080

  app:
    build: .
    command: >
      /bin/bash -c "
        rm -rf tmp/pids/server.pid &&
        rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - ssh
      - mail
    volumes:
      - .:/app:rw
      - $HOME:$HOME:ro
      - ssh:/ssh
      - cache:/app/tmp/cache
      - bundle_config:/app/.bundle
      - bundle:/usr/local/bundle
    ports:
      - $DOCKER_HOST_APP_PORT:3000
    environment:
      SSH_AUTH_SOCK: /ssh/auth/sock
      DATABASE_HOST: db
      MAIL_CATCHER_HOST: mail

  webapp:
    build: web-app
    command: npm start
    depends_on:
      - app
    volumes:
      - ./web-app:/app:rw
      - node_modules:/app/node_modules
    ports:
      - $DOCKER_HOST_WEBAPP_PORT:8080
    environment:
      APP_URL: http://app:3000
      DEV_SERVER_HOST: 0.0.0.0

  nginx:
    build: nginx
    depends_on:
      - app
    ports:
      - $DOCKER_HOST_NGINX_PORT:443
    volumes:
      - ./web-app:/webapp:ro
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro

volumes:
  db:
    driver: local
  ssh:
    driver: local
  bundle_config:
    driver: local
  node_modules:
    driver: local
  bundle:
    driver: local
  cache:
    driver: local
