default: &default
  adapter: mysql2
  charset: utf8mb4
  collation: utf8mb4_bin
  encoding: utf8mb4
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %> 
  username: <%= ENV.fetch('DATABASE_USERNAME') { 'root' } %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: material-collection_development

test:
  <<: *default
  database: material-collection_test

production:
  <<: *default
  database: material-collection_production
